#FROM store/oracle/weblogic:12.2.1.3-dev-200127

FROM oracle/weblogic:12.2.1.3-developer

MAINTAINER Alexandru Andrei Dabija

#Add Certificato
COPY weblogic12/certificato/* /u01/oracle/user_projects/domains/base_domain/security/

COPY weblogic12/base_domain/bin* /u01/oracle/user_projects/domains/base_domain/bin/

USER root
RUN   ls -lrth /u01/oracle/user_projects/domains/base_domain/ && \
      chown oracle:oracle -R /u01/oracle/user_projects/domains/base_domain && \
      chmod -R a+xwr /u01/oracle/user_projects/domains/base_domain && \
      ls -lrth /u01/oracle/user_projects/domains/base_domain/

USER oracle

#Install dependencies
#RUN useradd -ms /bin/bash oracle

#CMD ["createServer.sh"]
