version: '3'

services:
  tomcat1:
    container_name: tomcat-be
    #restart: on-failure
    #restart: always

    build:
      context: .
      dockerfile: Dockerfile-tomcat

    networks:
      local:
         ipv4_address: 172.20.0.3

    ports:
      - 8081:8080
      - 8009:8009

    extra_hosts:
     - oracle.external:10.206.198.93


    volumes:
      - /opt/docker/toolkit/tomcat/webapps/:/usr/local/tomcat/webapps/

      - /opt/docker/toolkit/tomcat/nodo1/conf/server.xml:/usr/local/tomcat/conf/server.xml
      - /opt/docker/toolkit/tomcat/nodo1/conf/context.xml:/usr/local/tomcat/conf/context.xml
      - /opt/docker/toolkit/tomcat/nodo1/conf/Catalina/:/usr/local/tomcat/conf/Catalina/
      - /opt/docker/toolkit/tomcat/nodo1/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      #- /opt/docker/toolkit/tomcat/lib/:/usr/local/tomcat/lib/

      - /opt/docker/toolkit/volumes/server_logs/:/usr/local/tomcat/logs/

      - /opt/docker/toolkit/volumes/application_configurations/:/opt/application_configurations/
      - /opt/docker/toolkit/volumes/application_logs/:/opt/application_logs/
    environment:
      - CATALINA_OPTS="-Djava.security.properties=/usr/local/tomcat/fastersecurerandom.properties -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -XX:+UseG1GC -Xms1024M -Xmx5120M"

  nginx:
    container_name: nginx-fe
    #restart: always
    build:
      context: .
      dockerfile: Dockerfile-nginx

    networks:
      local:
         ipv4_address: 172.20.0.2

    ports:
      - 80:80
      - 443:443

    extra_hosts:
     - srv.1:172.20.0.3
     - srv.2:172.20.0.4

     - tail.app1:172.20.0.10
     - tail.app2:172.20.0.11

     - tail.docker:172.20.0.20
     - tail.srv.1:172.20.0.21
     - tail.srv.2:172.20.0.22

     - tail.nginx.info:172.20.0.22
     - tail.nginx.error:172.20.0.22

    #links:
    #  - tomcat1

    depends_on:
      - tomcat1

    volumes:
      - /opt/docker/toolkit/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /opt/docker/toolkit/nginx/logs/:/var/log/nginx
      - /opt/docker/toolkit/nginx/www/:/usr/share/nginx/www/
      - /opt/docker/toolkit/nginx/html/:/usr/share/nginx/html/

    environment:
      - NGINX_HTTP_PORT_NUMBER=80
      - NGINX_HTTPS_PORT_NUMBER=443

networks:
  local:
    ipam:
      config:
        - subnet: 172.20.0.0/24
