version: '3'

services:
  weblogic12213:
    container_name: wlsnode01
    #restart: on-failure
    #restart: always

    #build:
    #  context: .
    #  dockerfile: Dockerfile-weblogic12213

    image: weblogic12212_weblogic12213:latest

    networks:
      local:
         ipv4_address: 172.20.0.5

    ports:
      - 7001:8001
      - 9002:9002

    extra_hosts:
     - oracle.external:127.0.0.1

    #volumes:
      #- /opt/docker/toolkit/weblogic12/base_domain/:/u01/oracle/user_projects/domains/base_domain/
      #- /opt/docker/toolkit/weblogic12/docker_build/12.2.1.3/properties/domain.properties:/u01/oracle/properties/domain.properties
      #- /opt/docker/toolkit/volumes/application_configurations/:/opt/application_configurations/
      #- /opt/docker/toolkit/volumes/application_logs/:/opt/application_logs/


networks:
  local:
    ipam:
      config:
        - subnet: 172.20.0.0/24
