version: '3'

services:
  sonar:
    container_name: sonar
    #restart: on-failure
    #restart: always

    build:
      context: .
      dockerfile: Dockerfile-sonar

    command: -Dsonar.web.context=/sonar

    networks:
      local:
         ipv4_address: 172.20.0.7

    ports:
      - 9000:9000


    volumes:
      - /opt/docker/toolkit/volumes/sonar/sonarqube_conf:/opt/sonarqube/conf
      - /opt/docker/toolkit/volumes/sonar/sonarqube_data:/opt/sonarqube/data
      - /opt/docker/toolkit/volumes/sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - /opt/docker/toolkit/volumes/sonar/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins


networks:
  local:
    ipam:
      config:
        - subnet: 172.20.0.0/24
